// Generated by Skyramp v1.3.3 on 2026-01-22 06:00:16.859262 +0500 PKT m=+1614.883259835
// Command: skyramp generate smoke rest http://localhost:3000/api/brands \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output-dir /Users/qaisu/Downloads/nc-ecom/tests/skyramp/smoke \
// 		--overwrite \
// 		--response-status-code 200

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:3000";

// smoke test for /api/brands GET
test('testBrandsGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const brandsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/brands",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(brandsGetResponse.statusCode == 200).toBeTruthy();
});
