// Generated by Skyramp v1.3.3 on 2026-01-22 06:00:45.358059 +0500 PKT m=+1643.381915126
// Command: skyramp generate smoke rest http://localhost:3000/api/brands \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /Users/qaisu/Downloads/nc-ecom/tests/skyramp/smoke \
// 		--overwrite \
// 		--request-data {"name":"Test Brand","description":"Test Brand","logo_url":"https://example.com/logo.jpg","website_url":"https://example.com"} \
// 		--response-status-code 201

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:3000";

// smoke test for /api/brands POST
test('testBrandsPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const brandsPostRequestBody: string = `{
        "description": "Test Brand",
        "logo_url": "https://example.com/logo.jpg",
        "name": "Test Brand",
        "website_url": "https://example.com"
    }`;

    // Execute Request
    const brandsPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/brands",
        method: "POST",
        body: brandsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(brandsPostResponse.statusCode == 201).toBeTruthy();
});
