// Generated by Skyramp v1.3.3 on 2026-01-22 06:00:50.958515 +0500 PKT m=+1648.982343210
// Command: skyramp generate smoke rest http://localhost:3000/api/bundles \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /Users/qaisu/Downloads/nc-ecom/tests/skyramp/smoke \
// 		--overwrite \
// 		--request-data {"name":"Test Bundle","description":"Test Bundle","bundle_price":500,"image_url":"https://example.com/bundle.jpg"} \
// 		--response-status-code 201

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:3000";

// smoke test for /api/bundles POST
test('testBundlesPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const bundlesPostRequestBody: string = `{
        "bundle_price": 500,
        "description": "Test Bundle",
        "image_url": "https://example.com/bundle.jpg",
        "name": "Test Bundle"
    }`;

    // Execute Request
    const bundlesPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/bundles",
        method: "POST",
        body: bundlesPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(bundlesPostResponse.statusCode == 201).toBeTruthy();
});
