// Generated by Skyramp v1.3.3 on 2026-01-22 06:00:52.727272 +0500 PKT m=+1650.751091376
// Command: skyramp generate smoke rest http://localhost:3000/api/cart \
// 		--auth-header auth-token \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /Users/qaisu/Downloads/nc-ecom/tests/skyramp/smoke \
// 		--overwrite \
// 		--request-data {"product_id":1,"quantity":1} \
// 		--response-status-code 200

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:3000";

// smoke test for /api/cart POST
test('testCartPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["auth-token"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const cartPostRequestBody: string = `{
        "product_id": 1,
        "quantity": 1
    }`;

    // Execute Request
    const cartPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/cart",
        method: "POST",
        body: cartPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(cartPostResponse.statusCode == 200).toBeTruthy();
});
