// Generated by Skyramp v1.3.3 on 2026-01-22 06:00:43.601332 +0500 PKT m=+1641.625196460
// Command: skyramp generate smoke rest http://localhost:3000/api/categories \
// 		--auth-header auth-token \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /Users/qaisu/Downloads/nc-ecom/tests/skyramp/smoke \
// 		--overwrite \
// 		--request-data {"name":"Test Category","slug":"test-category","description":"Test","image_url":"https://example.com/image.jpg"} \
// 		--response-status-code 201

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:3000";

// smoke test for /api/categories POST
test('testCategoriesPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["auth-token"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const categoriesPostRequestBody: string = `{
        "description": "Test",
        "image_url": "https://example.com/image.jpg",
        "name": "Test Category",
        "slug": "test-category"
    }`;

    // Execute Request
    const categoriesPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/categories",
        method: "POST",
        body: categoriesPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(categoriesPostResponse.statusCode == 201).toBeTruthy();
});
