// Generated by Skyramp v1.3.3 on 2026-01-22 06:00:47.259657 +0500 PKT m=+1645.283503418
// Command: skyramp generate smoke rest http://localhost:3000/api/discounts \
// 		--auth-header auth-token \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /Users/qaisu/Downloads/nc-ecom/tests/skyramp/smoke \
// 		--overwrite \
// 		--request-data {"code":"TEST10","name":"Test Discount","description":"Test","discount_type":"percentage","discount_value":"10","min_purchase_amount":100,"start_date":"2025-01-01","end_date":"2026-12-31"} \
// 		--response-status-code 201

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:3000";

// smoke test for /api/discounts POST
test('testDiscountsPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["auth-token"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const discountsPostRequestBody: string = `{
        "code": "TEST10",
        "description": "Test",
        "discount_type": "percentage",
        "discount_value": "10",
        "end_date": "2026-12-31",
        "min_purchase_amount": 100,
        "name": "Test Discount",
        "start_date": "2025-01-01"
    }`;

    // Execute Request
    const discountsPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/discounts",
        method: "POST",
        body: discountsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(discountsPostResponse.statusCode == 201).toBeTruthy();
});
