// Generated by Skyramp v1.3.3 on 2026-01-22 06:00:08.767832 +0500 PKT m=+1606.791869918
// Command: skyramp generate smoke rest http://localhost:3000/api/auth/me \
// 		--auth-header auth-token \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output-dir /Users/qaisu/Downloads/nc-ecom/tests/skyramp/smoke \
// 		--overwrite \
// 		--response-status-code 200

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:3000";

// smoke test for /api/auth/me GET
test('testMeGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["auth-token"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const meGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/auth/me",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(meGetResponse.statusCode == 200).toBeTruthy();
});
