// Generated by Skyramp v1.3.3 on 2026-01-22 06:00:59.152921 +0500 PKT m=+1657.176708501
// Command: skyramp generate smoke rest http://localhost:3000/api/orders \
// 		--auth-header auth-token \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /Users/qaisu/Downloads/nc-ecom/tests/skyramp/smoke \
// 		--overwrite \
// 		--request-data {"shipping_address":"123 Main St, City, Country","payment_method":"cash_on_delivery"} \
// 		--response-status-code 201

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:3000";

// smoke test for /api/orders POST
test('testOrdersPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["auth-token"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const ordersPostRequestBody: string = `{
        "payment_method": "cash_on_delivery",
        "shipping_address": "123 Main St, City, Country"
    }`;

    // Execute Request
    const ordersPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/orders",
        method: "POST",
        body: ordersPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(ordersPostResponse.statusCode == 201).toBeTruthy();
});
