// Generated by Skyramp v1.3.3 on 2026-01-22 06:00:41.828706 +0500 PKT m=+1639.852579001
// Command: skyramp generate smoke rest http://localhost:3000/api/products \
// 		--auth-header auth-token \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /Users/qaisu/Downloads/nc-ecom/tests/skyramp/smoke \
// 		--overwrite \
// 		--request-data {"brand_id":1,"category_id":1,"name":"Test Product","slug":"test-product","description":"Test","short_description":"Test","original_price":100,"current_price":80,"stock_quantity":10} \
// 		--response-status-code 201

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:3000";

// smoke test for /api/products POST
test('testProductsPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["auth-token"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const productsPostRequestBody: string = `{
        "brand_id": 1,
        "category_id": 1,
        "current_price": 80,
        "description": "Test",
        "name": "Test Product",
        "original_price": 100,
        "short_description": "Test",
        "slug": "test-product",
        "stock_quantity": 10
    }`;

    // Execute Request
    const productsPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/products",
        method: "POST",
        body: productsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(productsPostResponse.statusCode == 201).toBeTruthy();
});
