// Generated by Skyramp v1.3.3 on 2026-01-22 06:02:27.874662 +0500 PKT m=+1745.898007335
// Command: skyramp generate smoke rest http://localhost:3000/api/users/profile \
// 		--auth-header auth-token \
// 		--framework playwright \
// 		--language typescript \
// 		--method PUT \
// 		--output-dir /Users/qaisu/Downloads/nc-ecom/tests/skyramp/smoke \
// 		--overwrite \
// 		--request-data {"name":"Updated Profile","phone":"1234567890","address":"123 Main St","city":"New York","postal_code":"10001","country":"USA"} \
// 		--response-status-code 200

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:3000";

// smoke test for /api/users/profile PUT
test('testProfilePut', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["auth-token"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const profilePutRequestBody: string = `{
        "address": "123 Main St",
        "city": "New York",
        "country": "USA",
        "name": "Updated Profile",
        "phone": "1234567890",
        "postal_code": "10001"
    }`;

    // Execute Request
    const profilePutResponse = await client.sendRequest({
        url: URL,
        path: "/api/users/profile",
        method: "PUT",
        body: profilePutRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(profilePutResponse.statusCode == 200).toBeTruthy();
});
