// Generated by Skyramp v1.3.3 on 2026-01-22 05:59:52.893587 +0500 PKT m=+1590.917704418
// Command: skyramp generate smoke rest http://localhost:3000/api/auth/signin \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /Users/qaisu/Downloads/nc-ecom/tests/skyramp/smoke \
// 		--overwrite \
// 		--request-data {"email":"admin@namecheap.com","password":"admin123"} \
// 		--response-status-code 200

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:3000";

// smoke test for /api/auth/signin POST
test('testSigninPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const signinPostRequestBody: string = `{
        "email": "admin@namecheap.com",
        "password": "admin123"
    }`;

    // Execute Request
    const signinPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/auth/signin",
        method: "POST",
        body: signinPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(signinPostResponse.statusCode == 200).toBeTruthy();
});
