// Generated by Skyramp v1.3.3 on 2026-01-22 06:00:06.167036 +0500 PKT m=+1604.191086960
// Command: skyramp generate smoke rest http://localhost:3000/api/auth/signup \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /Users/qaisu/Downloads/nc-ecom/tests/skyramp/smoke \
// 		--overwrite \
// 		--request-data {"email":"testuser@test.com","password":"test123","name":"Test User"} \
// 		--response-status-code 200

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:3000";

// smoke test for /api/auth/signup POST
test('testSignupPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const signupPostRequestBody: string = `{
        "email": "testuser@test.com",
        "name": "Test User",
        "password": "test123"
    }`;

    // Execute Request
    const signupPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/auth/signup",
        method: "POST",
        body: signupPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(signupPostResponse.statusCode == 200).toBeTruthy();
});
